<?php
// config/config.dist.php
//
// Default configuration template for RoundDAV.
// The installer (public/install.php) will copy this file to config.php
// and fill in the database DSN, user and password.

return [
    // Enable verbose errors and extra diagnostics.
    // Recommended: false in production, true while debugging.
    'debug' => false,

    // Database connection. These values will be overwritten by the installer.
    'database' => [
        // DSN will be generated by the installer using the host/dbname you provide.
        'dsn'      => 'mysql:host=localhost;dbname=rounddav;charset=utf8mb4',
        'user'     => 'rounddav',
        'password' => '',
        'options'  => [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ],
    ],

    // Base URI for the DAV endpoint. If left empty, it will be auto-detected
    // from the request (for example: /rounddav/public/).
    'base_uri' => '',

    // Basic file logging for provisioning / runtime errors.
    'log' => [
        // Set to false to completely disable logging.
        'enabled' => true,
        // Adjust to wherever you want logs to land. By default, keep it inside
        // the RoundDAV tree under var/logs/.
        'file'    => __DIR__ . '/../var/logs/rounddav.log',
    ],

    // Security / rate limiting knobs (wired for future RateLimiter logic).
    'security' => [
        'rate_limit' => [
            // Toggle rate limiting for API-style endpoints once implemented.
            'enabled'       => true,
            // Max requests allowed in the configured window from a single client.
            'max_requests'  => 100,
            // Sliding window size in seconds.
            'window_sec'    => 300,
            // How long (in minutes) a client should be blocked after exceeding the limit.
            'block_minutes' => 30,
        ],
    ],

    // Admin UI credentials for /public/admin/.
    // For security, the installer will generate a password hash using password_hash()
    // and write it here. Leaving password_hash empty disables login.
    'admin' => [
        'username'      => 'admin',
        'email'         => '',
        'password'		=> '', // legacy plain-text identifier (mirrors email for compatibility)
        'password_hash' => '',
    ],

    // Provisioning API settings (used by the Roundcube rounddav_provision plugin).
    'provision' => [
        // Shared secret for the X-RoundDAV-Token header. Change this to a long random string.
        'shared_secret'    => 'change_me_provision',
        // Prefix for principal URIs; the default works with the shipped schema.
        'principal_prefix' => 'principals',
    ],

    // Optional SSO integration for Roundcube (rounddav_provision plugin).
    'sso' => [
        // Enable/disable SSO. When disabled, Roundcube will fall back to plain URLs.
        'enabled' => true,

        // Shared secret used to sign login/logout tokens.
        // This MUST match the rounddav_sso_secret value in the Roundcube
        // rounddav_provision plugin config.inc.php.
        'secret'  => 'change_me_sso',

        // Token lifetime in seconds (default: 10 minutes).
        'ttl'     => 600,
    ],

    // Optional WebDAV file storage. When enabled, a /files collection is exposed
    // and the web UI under /public/files/ uses this path for user/shared storage.
    'files' => [
        'enabled' => false,
        // Adjust to a directory outside your web root, writable by the web server user.
        'root'    => '/srv/rounddav-files',
    ],

    // Bookmarks engine (Roundcube integration + optional API access)
    'bookmarks' => [
        'enabled'                => true,
        // Per-user + per-domain safety limits (0 = unlimited)
        'max_private_per_user'   => 1000,
        'max_shared_per_domain'  => 4000,
        // Defaults for new domains (can be overridden in admin UI)
        'shared_default_enabled' => true,
        'shared_default_label'   => 'Shared Bookmarks',
        // Favicon fetching limits / timeouts (bytes, seconds)
        'max_favicon_bytes'      => 24576,
        'max_inline_icon_bytes'  => 8192,
        'favicon_timeout'        => 4,
        // Optional dedicated API shared secret; falls back to provision.shared_secret.
        'shared_secret'          => '',
    ],

    // Global collections config (for future shared addressbooks/calendars).
    'globals' => [
        'addressbooks' => [],
        'calendars'    => [],
    ],

    // Localization
    'locale' => [
        'default' => 'en_US',
    ],
];
